#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condez_SIS_v2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DcondezSISDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDBCONDEZ(DBCONDEZ instance);
    partial void UpdateDBCONDEZ(DBCONDEZ instance);
    partial void DeleteDBCONDEZ(DBCONDEZ instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Condez_SIS_v2.Properties.Settings.Default.DcondezSISDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DBCONDEZ> DBCONDEZs
		{
			get
			{
				return this.GetTable<DBCONDEZ>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DeleleStudent")]
		public int sp_DeleleStudent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUDENT_NO", DbType="VarChar(20)")] string sTUDENT_NO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTUDENT_NO);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertStudent")]
		public int sp_InsertStudent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAMEOFSTUDENT", DbType="VarChar(50)")] string nAMEOFSTUDENT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEARSECTIONMAJOR", DbType="VarChar(250)")] string yEARSECTIONMAJOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COURSE", DbType="VarChar(50)")] string cOURSE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BIRTHDAY", DbType="Date")] System.Nullable<System.DateTime> bIRTHDAY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACTNUMBER", DbType="VarChar(50)")] string cONTACTNUMBER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRESS", DbType="VarChar(50)")] string aDDRESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACTPERSON", DbType="VarChar(50)")] string cONTACTPERSON, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACTPERSONADDRESS", DbType="VarChar(50)")] string cONTACTPERSONADDRESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACTPERSONNUMBER", DbType="VarChar(50)")] string cONTACTPERSONNUMBER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentImage", DbType="VarBinary(MAX)")] System.Data.Linq.Binary studentImage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nAMEOFSTUDENT, yEARSECTIONMAJOR, cOURSE, bIRTHDAY, cONTACTNUMBER, aDDRESS, cONTACTPERSON, cONTACTPERSONADDRESS, cONTACTPERSONNUMBER, studentImage);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_updatestudent")]
		public int sp_updatestudent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUDENT_NO", DbType="VarChar(20)")] string sTUDENT_NO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAMEOFSTUDENT", DbType="VarChar(50)")] string nAMEOFSTUDENT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEARSECTIONMAJOR", DbType="VarChar(250)")] string yEARSECTIONMAJOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COURSE", DbType="VarChar(50)")] string cOURSE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BIRTHDAY", DbType="Date")] System.Nullable<System.DateTime> bIRTHDAY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACTNUMBER", DbType="VarChar(50)")] string cONTACTNUMBER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRESS", DbType="VarChar(50)")] string aDDRESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACTPERSON", DbType="VarChar(50)")] string cONTACTPERSON, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACTPERSONADDRESS", DbType="VarChar(50)")] string cONTACTPERSONADDRESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACTPERSONNUMBER", DbType="VarChar(50)")] string cONTACTPERSONNUMBER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentImage", DbType="VarBinary(MAX)")] System.Data.Linq.Binary studentImage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTUDENT_NO, nAMEOFSTUDENT, yEARSECTIONMAJOR, cOURSE, bIRTHDAY, cONTACTNUMBER, aDDRESS, cONTACTPERSON, cONTACTPERSONADDRESS, cONTACTPERSONNUMBER, studentImage);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBCONDEZ")]
	public partial class DBCONDEZ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STUDENT_NO;
		
		private string _NAMEOFSTUDENT;
		
		private string _YEARSECTIONMAJOR;
		
		private string _COURSE;
		
		private System.Nullable<System.DateTime> _BIRTHDAY;
		
		private string _CONTACTNUMBER;
		
		private string _ADDRESS;
		
		private string _CONTACTPERSON;
		
		private string _CONTACTPERSONADDRESS;
		
		private string _CONTACTPERSONNUMBER;
		
		private System.Data.Linq.Binary _StudentImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTUDENT_NOChanging(int value);
    partial void OnSTUDENT_NOChanged();
    partial void OnNAMEOFSTUDENTChanging(string value);
    partial void OnNAMEOFSTUDENTChanged();
    partial void OnYEARSECTIONMAJORChanging(string value);
    partial void OnYEARSECTIONMAJORChanged();
    partial void OnCOURSEChanging(string value);
    partial void OnCOURSEChanged();
    partial void OnBIRTHDAYChanging(System.Nullable<System.DateTime> value);
    partial void OnBIRTHDAYChanged();
    partial void OnCONTACTNUMBERChanging(string value);
    partial void OnCONTACTNUMBERChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnCONTACTPERSONChanging(string value);
    partial void OnCONTACTPERSONChanged();
    partial void OnCONTACTPERSONADDRESSChanging(string value);
    partial void OnCONTACTPERSONADDRESSChanged();
    partial void OnCONTACTPERSONNUMBERChanging(string value);
    partial void OnCONTACTPERSONNUMBERChanged();
    partial void OnStudentImageChanging(System.Data.Linq.Binary value);
    partial void OnStudentImageChanged();
    #endregion
		
		public DBCONDEZ()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDENT_NO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STUDENT_NO
		{
			get
			{
				return this._STUDENT_NO;
			}
			set
			{
				if ((this._STUDENT_NO != value))
				{
					this.OnSTUDENT_NOChanging(value);
					this.SendPropertyChanging();
					this._STUDENT_NO = value;
					this.SendPropertyChanged("STUDENT_NO");
					this.OnSTUDENT_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMEOFSTUDENT", DbType="NVarChar(50)")]
		public string NAMEOFSTUDENT
		{
			get
			{
				return this._NAMEOFSTUDENT;
			}
			set
			{
				if ((this._NAMEOFSTUDENT != value))
				{
					this.OnNAMEOFSTUDENTChanging(value);
					this.SendPropertyChanging();
					this._NAMEOFSTUDENT = value;
					this.SendPropertyChanged("NAMEOFSTUDENT");
					this.OnNAMEOFSTUDENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEARSECTIONMAJOR", DbType="NVarChar(50)")]
		public string YEARSECTIONMAJOR
		{
			get
			{
				return this._YEARSECTIONMAJOR;
			}
			set
			{
				if ((this._YEARSECTIONMAJOR != value))
				{
					this.OnYEARSECTIONMAJORChanging(value);
					this.SendPropertyChanging();
					this._YEARSECTIONMAJOR = value;
					this.SendPropertyChanged("YEARSECTIONMAJOR");
					this.OnYEARSECTIONMAJORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COURSE", DbType="NVarChar(50)")]
		public string COURSE
		{
			get
			{
				return this._COURSE;
			}
			set
			{
				if ((this._COURSE != value))
				{
					this.OnCOURSEChanging(value);
					this.SendPropertyChanging();
					this._COURSE = value;
					this.SendPropertyChanged("COURSE");
					this.OnCOURSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHDAY", DbType="Date")]
		public System.Nullable<System.DateTime> BIRTHDAY
		{
			get
			{
				return this._BIRTHDAY;
			}
			set
			{
				if ((this._BIRTHDAY != value))
				{
					this.OnBIRTHDAYChanging(value);
					this.SendPropertyChanging();
					this._BIRTHDAY = value;
					this.SendPropertyChanged("BIRTHDAY");
					this.OnBIRTHDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACTNUMBER", DbType="NVarChar(50)")]
		public string CONTACTNUMBER
		{
			get
			{
				return this._CONTACTNUMBER;
			}
			set
			{
				if ((this._CONTACTNUMBER != value))
				{
					this.OnCONTACTNUMBERChanging(value);
					this.SendPropertyChanging();
					this._CONTACTNUMBER = value;
					this.SendPropertyChanged("CONTACTNUMBER");
					this.OnCONTACTNUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(50)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACTPERSON", DbType="NVarChar(50)")]
		public string CONTACTPERSON
		{
			get
			{
				return this._CONTACTPERSON;
			}
			set
			{
				if ((this._CONTACTPERSON != value))
				{
					this.OnCONTACTPERSONChanging(value);
					this.SendPropertyChanging();
					this._CONTACTPERSON = value;
					this.SendPropertyChanged("CONTACTPERSON");
					this.OnCONTACTPERSONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACTPERSONADDRESS", DbType="NVarChar(50)")]
		public string CONTACTPERSONADDRESS
		{
			get
			{
				return this._CONTACTPERSONADDRESS;
			}
			set
			{
				if ((this._CONTACTPERSONADDRESS != value))
				{
					this.OnCONTACTPERSONADDRESSChanging(value);
					this.SendPropertyChanging();
					this._CONTACTPERSONADDRESS = value;
					this.SendPropertyChanged("CONTACTPERSONADDRESS");
					this.OnCONTACTPERSONADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACTPERSONNUMBER", DbType="NVarChar(50)")]
		public string CONTACTPERSONNUMBER
		{
			get
			{
				return this._CONTACTPERSONNUMBER;
			}
			set
			{
				if ((this._CONTACTPERSONNUMBER != value))
				{
					this.OnCONTACTPERSONNUMBERChanging(value);
					this.SendPropertyChanging();
					this._CONTACTPERSONNUMBER = value;
					this.SendPropertyChanged("CONTACTPERSONNUMBER");
					this.OnCONTACTPERSONNUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentImage", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary StudentImage
		{
			get
			{
				return this._StudentImage;
			}
			set
			{
				if ((this._StudentImage != value))
				{
					this.OnStudentImageChanging(value);
					this.SendPropertyChanging();
					this._StudentImage = value;
					this.SendPropertyChanged("StudentImage");
					this.OnStudentImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
